### ISSUE TITLE
Use Origin Trial token

### ISSUE THREAD

**Issue by beaufortfrancois** [YUKAI/konashi-web-bluetooth#6]
So that users of https://yukai.github.io/konashi-web-bluetooth/ don't have to enable the Web Bluetooth flag, you may want to request an Origin Trial token at http://bit.ly/WebBluetoothOriginTrial and simply add it to your HTML.

See https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web#available-for-origin-trials

**Comment by kiryuxxu** [comment]
@beaufortfrancois Thanks! I didn't know about token things. Going to check the documentation then.

**Comment by beaufortfrancois** [comment]
I'm looking forward to see this.
And if you need any help, please let me know.

**Comment by kiryuxxu** [comment]
@beaufortfrancois I still can't see any response to my email address _kiryu AT ux-xu.com_ . What's the problem?

**Comment by beaufortfrancois** [comment]
I believe your token should arrive soon now.

**Comment by beaufortfrancois** [comment]
I just got confirmation from the Origin Trial team that the token was already sent.
Can you check in your spam maybe?
If you still can't find it, I can share it with you by email if you want.

**Comment by kiryuxxu** [comment]
@beaufortfrancois Sorry, I just found the 2 emails in my inbox. Thank you so much!
